Dodanie podstawowego widoku miesiąca
jarekkopaczewski/Planer pull request #3
Opened 2022-03-12 18:49 UTC by paolo2000h

2022-03-12 19:20 UTC, M-Szymczyk commented on app/src/main/java/skills/future/planer/ui/month/MonthFragment.java
> +    public String getDate() {
Użyj wtyczki lombock - chyba tak to się pisze

2022-03-12 19:22 UTC, M-Szymczyk requested changes
Ogarnij tą wtyczkę

2022-03-13 22:31 UTC, jarekkopaczewski commented
Wygląda ok - wtyczka do dodanie później,

2022-03-13 22:33 UTC, danielglazer26 commented
Jest w porządku

2022-03-13 22:35 UTC, danielglazer26 approved these changes

2022-03-14 13:06 UTC, merged